### ISSUE TITLE
How do I get it to work on 2.1?

### ISSUE THREAD

**Issue by ignacy0109** [tsudoko/kanjigrid#2]
I put Kanji_grid.py in anki 2.1 addons directory (created new folder there), added __init__.py and Anki lists it among the addons but I still don't see any way to generate kanji grid (yes, I did restart Anki). Even tried to copy Kanji_grid.py's contents to __init__.py but still it doesn't work.

**Comment by tsudoko** [comment]
```
~/.local/share/Anki2/addons21 $ mkdir Kanji_grid
~/.local/share/Anki2/addons21 $ cp ~/.src/kanjigrid/Kanji_grid.py Kanji_grid/__init__.py
```

![image](https://i.imgur.com/LaP369s.png)

Works for me™, tested on 2.1.0beta37.

**Comment by ignacy0109** [comment]
Yeah, I'm retarded, Notepad++ doesn't save changes when you close it so I didn't actually copy the contents.

**Comment by rimusa** [comment]
I know that this issue is closed, but it would be nice to have the explanation on how to get it running in the README file.
