### ISSUE TITLE
cannot import name QStandardPaths

### ISSUE THREAD

**Issue by picsi** [tsudoko/kanjigrid#3]
Just tried it out and got this error:

    Traceback (most recent call last):
      File "aqt/addons.py", line 41, in loadAddons
      File "/home/foo/.local/share/Anki2/addons/kanji-grid.py", line 15, in <module>
        from aqt.qt import (QAction, QStandardPaths,
    ImportError: cannot import name QStandardPaths

**Comment by tsudoko** [comment]
> Compatible with Anki 2.1+

> All non-master branches are compatible with the pre-2.1 version.

If you want to use this addon with Anki <2.1, you'll need to pick the feature branches you want yourself. If you just want all new features, you can use the newly introduced [anki20](https://github.com/tsudoko/kanjigrid/tree/anki20) branch.

I have to admit, I didn't expect Anki 2.1 to be in the testing stage for so long.

**Comment by picsi** [comment]
Thanks!
